version: '3'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups


  django:
    build: .
    command: /start.sh
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
